# spell name translator
# Huge thanks to Ordos for the zmud-version
# almost as great thanks to the regexp-capable text editor... 
# translation to tf done by me:
# Antti Pietikäinen (heidel@operamail.com)
# 20.6.2005

#echo ### TARMALEN SPELLS ###
/def -F -i -P1BCcyan  -t"'(nilaehz arzocupne)'"                  translator_1=/substitute %{*} (Blessing of tarmalen)
/def -F -i -P1BCwhite -t"'(judicandus mangenic)'"                translator_2=/substitute %{*} (Cure critical wounds)
/def -F -i -P1BCwhite -t"'(judicandus mercuree)'"                translator_3=/substitute %{*} (Cure light wounds)
/def -F -i -P1BCwhite -t"'(freudemas egoid)'"                    translator_4=/substitute %{*} (Cure player)
/def -F -i -P1BCwhite -t"'(judicandus ignius)'"                  translator_5=/substitute %{*} (Cure serious wounds)
/def -F -i -P1BCcyan  -t"'(nilaehz temnahecne neg)'"             translator_6=/substitute %{*} (Curse of tarmalen)
/def -F -i -P1BCcyan  -t"'(mumbo jumbo)'"                        translator_7=/substitute %{*} (Deaths door)
/def -F -i -P1Ccyan   -t"'(annihilar hzzz golum)'"               translator_8=/substitute %{*} (Detect alignment)
/def -F -i -P1Ccyan   -t"'(misery ior noctar report)'"           translator_9=/substitute %{*} (Detect misery)
#echo ENHANCED VITALITY
/def -F -i -P1Ccyan   -t"'(Judicandee iocus merciaa Tarmalen)'"  translator_10=/substitute %{*} (Guardian angel)
/def -F -i -P1BCwhite -t"'(koko mudi kuntoon, hep)'"             translator_11=/substitute %{*} (Heal all)
/def -F -i -P1Ccyan   -t"'(Avee Alee adudaaa..)'"                translator_12=/substitute %{*} (Holy way)
/def -F -i -P1BCcyan  -t"'(Impuqueto es Bien)'"                  translator_13=/substitute %{*} (Lessen poison)
/def -F -i -P1BCcyan  -t"'(Corporem Connecticut Corporee)'"      translator_14=/substitute %{*} (Life link)
/def -F -i -P1Ccyan   -t"'(ful)'"                                translator_15=/substitute %{*} (Light)
/def -F -i -P1BCwhite -t"'(judicandus pafzarmus)'"               translator_16=/substitute %{*} (Major heal)
/def -F -i -P1BCwhite -t"'(judicandus puorgo mangenic)'"         translator_17=/substitute %{*} (Major party heal)
/def -F -i -P1BCwhite -t"'(judicandus pzarcumus)'"               translator_18=/substitute %{*} (Minor heal)
/def -F -i -P1BCwhite -t"'(judicandus puorgo ignius)'"           translator_19=/substitute %{*} (Minor party heal)
/def -F -i -P1Ccyan   -t"'(daaa timaaa of daaa maaanth)'"        translator_20=/substitute %{*} (Moon sense)
/def -F -i -P1BCcyan  -t"'(Naturallis Judicandus Imellys)'"      translator_21=/substitute %{*} (Natural renewal)
#echo NEW BODY
/def -F -i -P1Ccyan  -t"'(vokinsalak elfirtluassa)'"             translator_22=/substitute %{*} (Raise dead)
/def -F -i -P1BCwhite -t"'(judicandus saugaiii)'"                translator_23=/substitute %{*} (Remove poison)
/def -F -i -P1Ccyan  -t"'(lkzaz zueei enz orn)'"                 translator_24=/substitute %{*} (Remove scar)
/def -F -i -P1Ccyan  -t"'(Siwa on selvaa saastoa)'"              translator_25=/substitute %{*} (Restore)
/def -F -i -P1Ccyan  -t"'(tuo fo wen stanhc)'"                   translator_26=/substitute %{*} (Resurrect)
/def -F -i -P1BCcyan -t"'(Creo Herbamus Satisfus)'"              translator_27=/substitute %{*} (Satiate person)
/def -F -i -P1Ccyan  -t"'(ogyawaelbirroh)'"                      translator_28=/substitute %{*} (See the light)
/def -F -i -P1Ccyan  -t"'(likz az zurgeeon)'"                    translator_29=/substitute %{*} (Sex change)
/def -F -i -P1Ccyan  -t"'(naxanhar hecnatemne)'"                 translator_30=/substitute %{*} (Soul hold)
/def -F -i -P1BCcyan -t"'(gwwaaajj)'"                            translator_31=/substitute %{*} (Summon)
/def -F -i -P1BCwhite -t"'(judicandus zapracus)'"                translator_32=/substitute %{*} (True heal)
/def -F -i -P1BCwhite -t"'(judicandus eurto mangenic)'"          translator_33=/substitute %{*} (True party heal)
/def -F -i -P1BCcyan -t"'(harnaxan temnahecne)'"                 translator_34=/substitute %{*} (Unpain)
/def -F -i -P1BCcyan -t"'(Paxus)'"                               translator_35=/substitute %{*} (Unstun)
/def -F -i -P1Ccyan  -t"'(Jeeeeeeeeeeeesuuuuuuuus)'"             translator_36=/substitute %{*} (Water walking)

#echo ### PSIONICIST SPELLS ###
/def -F -i -P1Ccyan  -t"'(fooohh haaahhh booooloooooh)'"         translator_37=/substitute %{*} (Aura detection)
/def -F -i -P1Ccyan  -t"'(na ful)'"                              translator_38=/substitute %{*} (Darkness)
/def -F -i -P1BCcyan -t"'(transformaticus minimus)'"             translator_39=/substitute %{*} (Feather weight)
/def -F -i -P1BCblue -t"'(wheeeaaaaaa oooooo)'"                  translator_40=/substitute %{*} (Field of fear)
/def -F -i -P1Ccyan  -t"'(lentavia lauseita)'"                   translator_41=/substitute %{*} (Floating letters)
/def -F -i -P1BCblue -t"'(xulu tango charlie)'"                  translator_42=/substitute %{*} (Force dome)
/def -F -i -P1BCblue -t"'(thoiiiiiisss huuuiahashn)'"            translator_43=/substitute %{*} (Force shield)
/def -F -i -P1BCblue -t"'(sulta taiat pois, mulle hyva mieli taikadaikaduu)'" translator_44=/substitute %{*} (Forget)
/def -F -i -P1BCwhite -t"'(judicandus littleee)'"                translator_45=/substitute %{*} (Heal self)
/def -F -i -P1BCcyan -t"'(..... .... ... ..  .    .!)'"          translator_46=/substitute %{*} (Invisibility)
/def -F -i -P1BCcyan -t"'(nostaaaanndiz noszum)'"                translator_47=/substitute %{*} (Iron will)
/def -F -i -P1BCblue -t"'(vaxtextraktdryck)'"                    translator_49=/substitute %{*} (Mental glance)
/def -F -i -P1BCblue -t"'(kakakaaa tsooon)'"                     translator_50=/substitute %{*} (Mental watch)
/def -F -i -P1BCblue -t"'(omm zur fehh)'"                        translator_51=/substitute %{*} (Mind blast)
/def -F -i -P1BCblue -t"'(Annatheer graaweizta)'"                translator_52=/substitute %{*} (Mind development)
/def -F -i -P1BCblue -t"'(omm mar nak semen)'"                   translator_53=/substitute %{*} (Mind disruption)
/def -F -i -P1BCblue -t"'(memono locati)'"                       translator_54=/substitute %{*} (Mind store)
/def -F -i -P1BCblue -t"'(diir mieelis sxil miarr mieelin)'"     translator_55=/substitute %{*} (Mindseize)
/def -F -i -P1BCcyan -t"'(peilikuvia ja lasinsirpaleita)'"       translator_56=/substitute %{*} (Mirror image)
/def -F -i -P1BCblue -t"'(vorek ky taree)'"                      translator_57=/substitute %{*} (Paralyze)
/def -F -i -P1BCblue -t"'(omm zur semen)'"                       translator_59=/substitute %{*} (Psi blast)
/def -F -i -P1BCblue -t"'(omm zur sanc)'"                        translator_60=/substitute %{*} (Psibolt)
/def -F -i -P1BCblue -t"'(niihek atierapip aj niiramaan aaffaj)'" translator_61=/substitute %{*} (Psionic shield)
/def -F -i -P1BCblue -t"'(tora tora tora)'"                      translator_62=/substitute %{*} (Psychic crush)
/def -F -i -P1BCblue -t"'(aamad ato naav aanarub atyak ala)'"    translator_63=/substitute %{*} (Psychic purge)
/def -F -i -P1BCblue -t"'(toughen da mind reeez un biis)'"       translator_64=/substitute %{*} (Psychic sanctuary)
/def -F -i -P1BCblue -t"'(omm zur semen gnatlnamauch)'"          translator_65=/substitute %{*} (Psychic shout)
/def -F -i -P1BCblue -t"'(omm mar nak grttzt gnatlnamauch)'"     translator_66=/substitute %{*} (Psychic storm)
/def -F -i -P1BCblue -t"'(moon fiksu, soot tyhma - opi tasta taika)'" translator_67=/substitute %{*} (Spellteaching)
/def -F -i -P1BCblue -t"'(BBBBOOOOOO!!!!)'"                      translator_68=/substitute %{*} (Terror)
/def -F -i -P1BCblue -t"'(jakki makupala)'"                      translator_69=/substitute %{*} (There not there)
/def -F -i -P1BCblue -t"'(nihenuak assaam no nek orrek)'"        translator_70=/substitute %{*} (Transmute self)
/def -F -i -P1BCblue -t"'(ragus on etsat mumixam!)'"             translator_71=/substitute %{*} (Unstable mutation)

#echo ### CHANNELLERS SPELLS ###
/def -F -i -P1Ccyan -t"'(Give my creation life!!)'"              translator_72=/substitute %{*} (Animate golem)
/def -F -i -P1BCmagenta -t"'(shar ryo den...Haa!)'"              translator_73=/substitute %{*} (Channelball)
/def -F -i -P1BCyellow -t"'(tsaibaa)'"                           translator_74=/substitute %{*} (Channelbolt)
/def -F -i -P1Cyellow -t"'(grhagrhagrhagrah gra gra Hyaa!)'"     translator_75=/substitute %{*} (Channelburn)
/def -F -i -P1BCmagenta -t"'(lecaps meeb nonnock)'"              translator_76=/substitute %{*} (Channelray)
/def -F -i -P1Cyellow -t"'(grinurb sdan imflagrum)'"             translator_77=/substitute %{*} (Channelspray)
/def -F -i -P1Ccyan -t"'(greeeenie fiiingerie)'"                 translator_78=/substitute %{*} (Create herb)
/def -F -i -P1Ccyan -t"'(na ful)'"                               translator_79=/substitute %{*} (Darkness)
/def -F -i -P1BCcyan -t"'(enfuego delmigo)'"                     translator_80=/substitute %{*} (Drain ally)
/def -F -i -P1BCcyan -t"'(enfuego delvivendo)'"                  translator_81=/substitute %{*} (Drain enemy)
/def -F -i -P1BCcyan -t"'(enfuego delcosa)'"                     translator_82=/substitute %{*} (Drain item)
/def -F -i -P1BCcyan -t"'(enfuegome delterra)'"                  translator_83=/substitute %{*} (Drain room)
/def -F -i -P1Cyellow -t"'(hhhnnnnnrrrrraaahhh!!)'"              translator_84=/substitute %{*} (Energy aura)
/def -F -i -P1Cred -t"'(hnnn....Urrgggg.....RRAAHH!!!)'"         translator_85=/substitute %{*} (Energy aura)
/def -F -i -P1Cblue -t"'(RRRRAAAAAHHRRRRGGGGGGHHH!!!!!)'"        translator_86=/substitute %{*} (Energy aura)
/def -F -i -P1Ccyan -t"'(incantar enfeugo aggriva)'"             translator_87=/substitute %{*} (Energy vortex)
/def -F -i -P1BCcyan -t"'(transformaticus minimus)'"             translator_88=/substitute %{*} (Feather weight)
/def -F -i -P1Cyellow -t"'(fah zur sanc)'"                       translator_89=/substitute %{*} (Firebolt)
/def -F -i -P1Cyellow -t"'(fah zur fehh)'"                       translator_90=/substitute %{*} (Flame arrow)
/def -F -i -P1Ccyan -t"'(rise Rise RISE)'"                       translator_91=/substitute %{*} (Floating)
/def -F -i -P1BCwhite -t"'(shalambala shoashu)'"                 translator_92=/substitute %{*} (Golem heal)
/def -F -i -P1Ccyan -t"'(vas na ful)'"                           translator_93=/substitute %{*} (Greater darkness)
/def -F -i -P1Ccyan -t"'(vas ful)'"                              translator_94=/substitute %{*} (Greater light)
/def -F -i -P1Ccyan -t"'(mega visa huijari)'"                    translator_95=/substitute %{*} (Identify)
/def -F -i -P1Ccyan -t"'(h'njya)'"                               translator_96=/substitute %{*} (Item dispersion shield)
/def -F -i -P1BCyellow -t"'(zot zur sanc)'"                      translator_98=/substitute %{*} (Lightning bolt)
/def -F -i -P1BCmagenta -t"'(gtzt zur fehh)'"                    translator_99=/substitute %{*} (Magic missile)
/def -F -i -P1BCcyan -t"'(riljya)'"                              translator_100=/substitute %{*} (Personal force field)
/def -F -i -P1BCcyan -t"'(enfuego delyo)'"                       translator_101=/substitute %{*} (Replenish ally)
/def -F -i -P1Ccyan -t"'(ahne paskianen olen ma kun taikuutta nahda tahdon)'" translator_102=/substitute %{*} (See magic)
/def -F -i -P1BCyellow -t"'(zot zur fehh)'"                      translator_103=/substitute %{*} (Shocking grasp)
/def -F -i -P1BCmagenta -t"'(gtzt zur sanc)'"                    translator_105=/substitute %{*} (Summon lesser spores)
/def -F -i -P1Ccyan -t"'(insignificus et gargantum alternos)'"   translator_106=/substitute %{*} (Transfor golem)

#echo ### TEMPLAR SPELLS ###
/def -F -i -P1BCcyan -t"'(Faerwon, grant your favor!)'"          translator_107=/substitute %{*} (Bless armament)
/def -F -i -P1BCcyan -t"'(Benedic, Faerwon, nos et haec tua dona quae de tua largitate sumus sumpturi)'" translator_108=/substitute %{*} (Blessing of faerwon)
/def -F -i -P1Ccyan  -t"'(annihilar hzzz golum)'"                translator_109=/substitute %{*} (Detect alignment)
/def -F -i -P1BCcyan -t"'(In the name of Faerwon, make this shield stronger)'" translator_110=/substitute %{*} (Divine enhancement)
/def -F -i -P1BCcyan -t"'(Renew our strength)'"                  translator_111=/substitute %{*} (Laying on hands)
/def -F -i -P1BCcyan -t"'(Grant your worshipper your protection)'" translator_114=/substitute %{*} (Shield of faith)

#echo ### PRIESTS SPELLS ###
/def -F -i -P1BCblack -t"'(yugzhrr paf)'"                        translator_115=/substitute %{*} (Aneurysm)
/def -F -i -P1BCblack -t"'(Feel your anger and strike with all your hatred. Use your aggressive feelings and let the hate flow through you.)'" translator_116=/substitute %{*} (Aura of hate)
/def -F -i -P1BCblack -t"'(Bastage)'"                            translator_117=/substitute %{*} (Bastardly balm)
/def -F -i -P1BCblack -t"'(rhuuuumm angotz klekltz)'"            translator_118=/substitute %{*} (Cause critical wounds)
/def -F -i -P1BCblack -t"'(tosi pieni neula)'"                   translator_119=/substitute %{*} (Cause light wounds)
/def -F -i -P1BCblack -t"'(rhuuuumm angotz amprltz)'"            translator_120=/substitute %{*} (Cause serious wounds)
/def -F -i -P1Ccyan   -t"'(Gawd DAMN IT!)'"                      translator_123=/substitute %{*} (Damn armament)
/def -F -i -P1BCblack -t"'(whoosy banzziii pal eeeiizz dooneb)'" translator_125=/substitute %{*} (Dispel good)
/def -F -i -P1BCblack -t"'(yugfzhrrr suuck suuuuuck suuuuuuuuuuck)'" translator_126=/substitute %{*} (Energy drain)
/def -F -i -P1BCcyan  -t"'(flzeeeziiiiying nyyyaaa)'"            translator_127=/substitute %{*} (Go)
/def -F -i -P1BCblack -t"'(PAF PAF PAF!)'"                       translator_128=/substitute %{*} (Harm body)
/def -F -i -P1BCblack -t"'(yugzhrr)'"                            translator_129=/substitute %{*} (Hemorrhage)
/def -F -i -P1BCcyan  -t"'(Ab sinestris, mortum demitteri)'"     translator_130=/substitute %{*} (Last rites)
/def -F -i -P1BCblack -t"'(viiltaja jaska)'"                     translator_131=/substitute %{*} (Make scar)
/def -F -i -P1BCblack -t"'(I HATE MAGIC)'"                       translator_132=/substitute %{*} (Mana drain)
/def -F -i -P1BCblack -t"'(Zmasching Pupkins's infanitsadnnes)'" translator_133=/substitute %{*} (Mellon collie)
/def -F -i -P1BCcyan  -t"'(buuuummbzdiiiiiibummm)'"              translator_134=/substitute %{*} (Mobile cannon)
#echo New body
/def -F -i -P1BCblack -t"'(Harken to me and hear my plea, disease is what I call to thee)'" translator_135=/substitute %{*} (Pestilence)
/def -F -i -P1BCcyan  -t"'(Good is dumb)'"                       translator_136=/substitute %{*} (Protection from good)
/def -F -i -P1BCblack -t"'(With this ring, i do deconsecrate thee)'" translator_139=/substitute %{*} (Unholy matrimony)

#echo ### TIGER SPELLS ###
/def -F -i -P1Ccyan  -t"'(tamakan natelo assim)'"                translator_140=/substitute %{*} (All-seeing eye)
/def -F -i -P1Cyellow -t"'(Polo Polomii)'"                       translator_143=/substitute %{*} (Flame fists)
/def -F -i -P1Ccyan  -t"'(sakenoivasta voimasta)'"               translator_144=/substitute %{*} (Haste)
/def -F -i -P1Ccyan  -t"'(demoni on pomoni)'"                    translator_145=/substitute %{*} (Infravision)
/def -F -i -P1Ccyan  -t"'(jumpiiz laika wabbitzz)'"              translator_147=/substitute %{*} (Quicksilver)
/def -F -i -P1Ccyan  -t"large circle to the air with .* '(Haii!)'" translator_148=/substitute %{*} (Shadow leap)
/def -F -i -P1BCcyan -t"shred.* air with .* '(Haii!)'"           translator_149=/substitute %{*} (Tiger claw)
/def -F -i -P1Ccyan  -t"'(Tiger Power!)'"                        translator_150=/substitute %{*} (Tiger mask)
/def -F -i -P1Ccyan  -t"'(Jeeeeeeeeeeeesuuuuuuuus)'"             translator_151=/substitute %{*} (Water walking)

#echo ### NAVIGATOR SPELLS ###
/def -F -i -P1BCcyan -t"'(havia kauhistus pois)'"                translator_152=/substitute %{*} (Banish)
/def -F -i -P1BCcyan -t"'(prtolala offf pwerrrr)'"               translator_153=/substitute %{*} (Dimension door)
/def -F -i -P1BCcyan -t"'(tonnikalaa)'"                          translator_155=/substitute %{*} (Heavy weight)
/def -F -i -P1BCcyan -t"'(xafe uurthq)'"                         translator_157=/substitute %{*} (Relocate)
/def -F -i -P1BCcyan -t"'(xafe xyyqh xckgandhuzqarr)'"           translator_159=/substitute %{*} (Teleport with error)
/def -F -i -P1BCcyan -t"'(xafe ayz xckgandhuzqarr)'"             translator_160=/substitute %{*} (Teleport without error)
/def -F -i -P1BCcyan -t"'(mad rad dar)'"                         translator_161=/substitute %{*} (Wizard eye)

#echo ### SPIDER SPELLS ###
/def -F -i -P1Ccyan  -t"'(Khizanth Arachnidus Vitalis)'"         translator_163=/substitute %{*} (Hunger of the spider)
/def -F -i -P1Cgreen -t"'(saugaiii)'"                            translator_165=/substitute %{*} (Poison)
/def -F -i -P1Ccyan  -t"'(ddt ddt ddt is good for you and me!)'" translator_166=/substitute %{*} (Poison cloud)
/def -F -i -P1Ccyan  -t"'(Khizanth Arachnidus Satisfusmus)'"     translator_167=/substitute %{*} (Prayer to the spider queen)
/def -F -i -P1Ccyan  -t"'(infernalicus thanatos arachnidos)'"    translator_169=/substitute %{*} (Spider demon banishment)
/def -F -i -P1Ccyan  -t"'(infernalicus nexus arachnid rex)'"     translator_170=/substitute %{*} (Spider demon channeling)
/def -F -i -P1Ccyan  -t"'(arachnid infernalicus arachnoidus demonicus)'" translator_171=/substitute %{*} (Spider demon conjuration)
/def -F -i -P1Ccyan  -t"'(infernalicus domus arachnid rex)'"     translator_172=/substitute %{*} (Spider demon control)
/def -F -i -P1Ccyan  -t"'(Khirsah Zokant Arachnidus)'"           translator_173=/substitute %{*} (Spider demon inquiry)
/def -F -i -P1Ccyan  -t"'(infernalicus domus arachnid rex magnos)'" translator_174=/substitute %{*} (Spider demon mass sacrifice)
#echo Spider demon sacrifice
/def -F -i -P1Ccyan  -t"'(infernalicus intellegus arachnidos)'"  translator_175=/substitute %{*} (Spider eye)
/def -F -i -P1Ccyan  -t"'(Khirsah Khazanth Arachinidus)'"        translator_176=/substitute %{*} (Spider gate)
/def -F -i -P1Ccyan  -t"'(infernalicus claravonticus arachnidos)'" translator_177=/substitute %{*} (Spider gaze)
/def -F -i -P1Ccyan  -t"'(infernalicus conjuratis arachnidos)'"  translator_178=/substitute %{*} (Spider servant)
/def -F -i -P1BCcyan -t"'(Khizanth Arachnidus Diametricus)'"     translator_179=/substitute %{*} (Spider touch)
/def -F -i -P1Ccyan  -t"'(Khizanth Arachnidus Walkitus)'"        translator_180=/substitute %{*} (Spider walk)
/def -F -i -P1Ccyan  -t"'(infernalicus thanatos arachnidos)'"    translator_181=/substitute %{*} (Spider web)
/def -F -i -P1Cgreen -t"'(Khizanth Arachnidus Iracundus)'"       translator_182=/substitute %{*} (Spider wrath)
/def -F -i -P1BCcyan -t"'(morri nam pantoloosa)'"                translator_183=/substitute %{*} (Toxic dilution)
/def -F -i -P1Ccyan  -t"'(May this become the blood of the Spider queen)'" translator_184=/substitute %{*} (Venom blade)

